# Generated by Django 5.0.4 on 2024-05-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_rename_text_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('delayed', 'Delayed'), ('started', 'Started'), ('ended', 'Ended'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
