# Generated by Django 5.0.4 on 2024-05-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_alter_membership_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='state',
            field=models.CharField(choices=[('REMOVED', 'Removed'), ('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING', max_length=100),
        ),
    ]
